### ISSUE TITLE
NaN % fail rate

### ISSUE THREAD

**Issue by SimonAlling** [bowald/chs-exam-statistics#5]
I stumbled upon a “NaN %” fail rate for [TDA555 Introduktion till funktionell programmering](http://tenta.bowald.se/#/search/statistics/TDA555/chart). Same behavior in Safari on iOS 11 and Chrome 70 on Android. I haven’t looked at the code, but the [detailed statistics](http://tenta.bowald.se/#/search/statistics/TDA555/percentage) seem to suggest that this specific instance arises from the exam of 2011-11-16. Maybe some kind of error handling or sanity check would be nice for such cases.

Great app btw!

**Comment by bowald** [comment]
Thank you for reporting this issue. I will look in to this. If you figure it out before me you are welcome to send PR, and also thanks for the feedback :)

**Comment by SimonAlling** [comment]
I think [this line](https://github.com/bowald/chs-exam-statistics/blob/master/src/js/StatisticCtrl.js#L136) is the culprit:

    examFailRate += exam.notPassed / (exam.three + exam.four + exam.five + exam.notPassed);

If `exam` had no attendees, that line says `examFailRate += 0 / 0;`, i.e. `examFailRate += NaN;`.

**Comment by bowald** [comment]
Fixed and deployed to [tenta.bowald.se](tenta.bowald.se)
