### ISSUE TITLE
Average fail rate calculation

### ISSUE THREAD

**Issue by SimonAlling** [bowald/chs-exam-statistics#6]
It seems to me that the average fail grade may not be correctly calculated. This depends on how "correctly" is defined, but these observations can be made:

## Observation 1

The "average fail rate" today is literally the average of the fail rates, which gives greater weight to results performed at exams with fewer attendees. Consider as an (artificial, but illustrative) example a course which has given one regular exam and one re-exam, with the following statistics:

### Regular exam

- U: 0
- 3: 99
- 4: 0
- 5: 0

### Re-exam

- U: 1
- 3: 0
- 4: 0
- 5: 0

In total, the exam has been taken 100 times, with 1 failure. There are two ways to define "average fail rate":
1. The average of the fail rates, i.e. (0 % + 100 %) / 2 = **50 %**. This definition is used in the app today.
2. The total number of failures over the total number of attempts, i.e. 1 / 100 = **1 %**.

It is not obvious to me which of the definitions is better/more representative, but my spontaneous choice would be 2.

## Observation 2

The "average grade" for passing performances is calculated analogously to definition 2 above, so one might expect the "average fail rate" to be calculated in the same way.

**Comment by bowald** [comment]
Good observations. I think my reasoning at the time to choose the method for fail rate as in definition 1 was to make "Fail Rate" differ from average grade. Otherwise both would be fairly similar and one could be skipped. However, I do agree with you that the second definition is more informative. I will have to plot definition 1 and definition 2 and take a decision based on that. Will post here when I have taken the time to look into this.

**Comment by SimonAlling** [comment]
Hm. I don't understand how one of them could be skipped should definition 2 be used for "average fail rate". The "average grade" seems to consider only passing performances, so it is not connected to fail rate at all, is it? (And the "average fail rate" obviously says nothing about the average score of passing performances.)

**Comment by bowald** [comment]
Hmm, you are right. I thought I had included U:s in the average grade, but apparently not.
I think I will change the Fail rate to your suggestion, I will give it a thought.

**Comment by SimonAlling** [comment]
Have you given it a thought? :)

**Comment by bowald** [comment]
Haha, yeah, and forgotten about it. I will implement and deploy the suggested change during easter.

**Comment by bowald** [comment]
Fail rate is now calculated as you suggested. It was implemented in PR: #8. It is also deployed to [tenta.bowald.se](http://tenta.bowald.se). Thank you very much for your contribution 👍
