### ISSUE TITLE
Data Source 404

### ISSUE THREAD

**Issue by nils-trubkin** [bowald/chs-exam-statistics#9]
Document Not Found
The document you requested does not exist. It might have been deleted.

**Comment by bowald** [comment]
yes, unfortunately Chalmers stopped publishing the results from LADOK around 1.5 years ago. 
It's still possible to request the data via email to ladok@chalmers.se but at that time it was no longer possible to automate it, not sure if it's possible now.

**Comment by nils-trubkin** [comment]
Should this really be closed? The app is practically useless without the data.
